#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("YouTubeDemo.Resource", IsApplication=true)]

namespace YouTubeDemo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int gray = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07001c
			public const int autoplay_checkbox = 2131165212;
			
			// aapt resource value: 0x7f070013
			public const int event_log = 2131165203;
			
			// aapt resource value: 0x7f070008
			public const int fullscreen_button = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int intent_list = 2131165193;
			
			// aapt resource value: 0x7f070007
			public const int landscape_fullscreen_checkbox = 2131165191;
			
			// aapt resource value: 0x7f070004
			public const int layout = 2131165188;
			
			// aapt resource value: 0x7f07001d
			public const int lightbox_checkbox = 2131165213;
			
			// aapt resource value: 0x7f07000c
			public const int list_item_disabled_text = 2131165196;
			
			// aapt resource value: 0x7f07000b
			public const int list_item_text = 2131165195;
			
			// aapt resource value: 0x7f070006
			public const int other_views = 2131165190;
			
			// aapt resource value: 0x7f070016
			public const int pause_button = 2131165206;
			
			// aapt resource value: 0x7f070015
			public const int play_button = 2131165205;
			
			// aapt resource value: 0x7f070005
			public const int player = 2131165189;
			
			// aapt resource value: 0x7f070001
			public const int player_fragment = 2131165185;
			
			// aapt resource value: 0x7f070017
			public const int skip_to_text = 2131165207;
			
			// aapt resource value: 0x7f07001a
			public const int start_index_text = 2131165210;
			
			// aapt resource value: 0x7f070019
			public const int start_playlist_button = 2131165209;
			
			// aapt resource value: 0x7f07001b
			public const int start_time_text = 2131165211;
			
			// aapt resource value: 0x7f070018
			public const int start_video_button = 2131165208;
			
			// aapt resource value: 0x7f07000d
			public const int state_text = 2131165197;
			
			// aapt resource value: 0x7f070012
			public const int style_chromeless = 2131165202;
			
			// aapt resource value: 0x7f070010
			public const int style_default = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int style_minimal = 2131165201;
			
			// aapt resource value: 0x7f07000f
			public const int style_radio_group = 2131165199;
			
			// aapt resource value: 0x7f070002
			public const int tutorial_text = 2131165186;
			
			// aapt resource value: 0x7f070014
			public const int video_chooser = 2131165204;
			
			// aapt resource value: 0x7f070000
			public const int view_container = 2131165184;
			
			// aapt resource value: 0x7f070003
			public const int youtube_fragment = 2131165187;
			
			// aapt resource value: 0x7f07000a
			public const int youtube_version_text = 2131165194;
			
			// aapt resource value: 0x7f07000e
			public const int youtube_view = 2131165198;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ActionBar = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Fragments = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int FullScreen = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Intents = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int list_item = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int PlayerControls = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int PlayerControlsContainer = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int PlayerView = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int StandAlone = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f05000e
			public const int actionbar_tutorial = 2131034126;
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050008
			public const int autoplay = 2131034120;
			
			// aapt resource value: 0x7f05001a
			public const int chromeless = 2131034138;
			
			// aapt resource value: 0x7f050018
			public const int def = 2131034136;
			
			// aapt resource value: 0x7f05000c
			public const int enter_fullscreen = 2131034124;
			
			// aapt resource value: 0x7f05000a
			public const int error_player = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int fullscreen_tutorial = 2131034123;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			// aapt resource value: 0x7f050010
			public const int intent_disabled = 2131034128;
			
			// aapt resource value: 0x7f05000f
			public const int intent_select = 2131034127;
			
			// aapt resource value: 0x7f05000d
			public const int landscape_fullscreen = 2131034125;
			
			// aapt resource value: 0x7f050009
			public const int lightbox_mode = 2131034121;
			
			// aapt resource value: 0x7f050019
			public const int minimal = 2131034137;
			
			// aapt resource value: 0x7f050014
			public const int pause = 2131034132;
			
			// aapt resource value: 0x7f050013
			public const int play = 2131034131;
			
			// aapt resource value: 0x7f050005
			public const int play_playlist = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int play_video = 2131034116;
			
			// aapt resource value: 0x7f050017
			public const int player_style = 2131034135;
			
			// aapt resource value: 0x7f050003
			public const int playerfragment_text = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int playerview_text = 2131034114;
			
			// aapt resource value: 0x7f050016
			public const int seconds = 2131034134;
			
			// aapt resource value: 0x7f050015
			public const int skip_to = 2131034133;
			
			// aapt resource value: 0x7f050006
			public const int start_index = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int start_time = 2131034119;
			
			// aapt resource value: 0x7f050011
			public const int youtube_currently_installed = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int youtube_not_installed = 2131034130;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int BlackNoBarsTheme = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int BlackNoTitleBarTheme = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int OverlayActionBarTheme = 2131099650;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
