#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("YouTubeDemo.Resource", IsApplication=true)]

namespace YouTubeDemo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050005
			public const int autoplay_checkbox = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int lightbox_checkbox = 2131034118;
			
			// aapt resource value: 0x7f050003
			public const int start_index_text = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int start_playlist_button = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int start_time_text = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int start_video_button = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int youtube_fragment = 2131034112;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int StandAlone = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040006
			public const int autoplay = 2130968582;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			// aapt resource value: 0x7f040007
			public const int lightbox_mode = 2130968583;
			
			// aapt resource value: 0x7f040003
			public const int play_playlist = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int play_video = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int start_index = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int start_time = 2130968581;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
