#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("YouTubeDemo.Resource", IsApplication=true)]

namespace YouTubeDemo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int gray = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060010
			public const int autoplay_checkbox = 2131099664;
			
			// aapt resource value: 0x7f060008
			public const int fullscreen_button = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int landscape_fullscreen_checkbox = 2131099655;
			
			// aapt resource value: 0x7f060004
			public const int layout = 2131099652;
			
			// aapt resource value: 0x7f060011
			public const int lightbox_checkbox = 2131099665;
			
			// aapt resource value: 0x7f06000a
			public const int list_item_disabled_text = 2131099658;
			
			// aapt resource value: 0x7f060009
			public const int list_item_text = 2131099657;
			
			// aapt resource value: 0x7f060006
			public const int other_views = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int player = 2131099653;
			
			// aapt resource value: 0x7f060001
			public const int player_fragment = 2131099649;
			
			// aapt resource value: 0x7f06000e
			public const int start_index_text = 2131099662;
			
			// aapt resource value: 0x7f06000d
			public const int start_playlist_button = 2131099661;
			
			// aapt resource value: 0x7f06000f
			public const int start_time_text = 2131099663;
			
			// aapt resource value: 0x7f06000c
			public const int start_video_button = 2131099660;
			
			// aapt resource value: 0x7f060002
			public const int tutorial_text = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int view_container = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int youtube_fragment = 2131099651;
			
			// aapt resource value: 0x7f06000b
			public const int youtube_view = 2131099659;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ActionBar = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Fragments = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int FullScreen = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int list_item = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int PlayerView = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int StandAlone = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f05000e
			public const int actionbar_tutorial = 2131034126;
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050008
			public const int autoplay = 2131034120;
			
			// aapt resource value: 0x7f05000c
			public const int enter_fullscreen = 2131034124;
			
			// aapt resource value: 0x7f05000a
			public const int error_player = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int fullscreen_tutorial = 2131034123;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			// aapt resource value: 0x7f05000d
			public const int landscape_fullscreen = 2131034125;
			
			// aapt resource value: 0x7f050009
			public const int lightbox_mode = 2131034121;
			
			// aapt resource value: 0x7f050005
			public const int play_playlist = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int play_video = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int playerfragment_text = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int playerview_text = 2131034114;
			
			// aapt resource value: 0x7f050006
			public const int start_index = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int start_time = 2131034119;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
